import Document, { Html, Head, Main, NextScript } from 'next/document';

class MyDocument extends Document {
	static async getInitialProps(ctx) {
		const initialProps = await Document.getInitialProps(ctx);
		return { ...initialProps };
	}

	render() {
		return (
			<Html height="100%">
				<Head>
					<link rel="icon" href="/icon.svg" />
					<meta
						name="description"
						content="Generated by create next app"
					/>
				</Head>

				<body height="100%">
					<Main />
					<NextScript />
				</body>
			</Html>
		);
	}
}

export default MyDocument;
